CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) NOT NULL,
    line_user_id VARCHAR(255) UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


